#pragma once

const std::string C_ID00 = "Luigi";
const std::string C_ID01 = "Master Chief";
const std::string C_ID02 = "Aizen";
const std::string C_ID03 = "Naruto";
const std::string C_ID04 = "Cyrax";
const std::string C_ID05 = "Shadow";
const std::string C_ID06 = "Spyro";
const std::string C_ID07 = "Roy";
const std::string C_ID08 = "Roxas";
const std::string C_ID09 = "Donald Trump";
const std::string C_ID10 = "Darth Vader";
const std::string C_ID11 = "Joker";
const std::string C_ID12 = "Emperor";
bool CharacterUnlock_ID00;
bool CharacterUnlock_ID01;
bool CharacterUnlock_ID02;
bool CharacterUnlock_ID03;
bool CharacterUnlock_ID04;
bool CharacterUnlock_ID05;
bool CharacterUnlock_ID06;
bool CharacterUnlock_ID07;
bool CharacterUnlock_ID08;
bool CharacterUnlock_ID09;
bool CharacterUnlock_ID10;
bool CharacterUnlock_ID11;
bool CharacterUnlock_ID12;
sf::Texture C_T_ID00;
sf::Texture C_T_ID01;
sf::Texture C_T_ID02;
sf::Texture C_T_ID03;
sf::Texture C_T_ID04;
sf::Texture C_T_ID05;
sf::Texture C_T_ID06;
sf::Texture C_T_ID07;
sf::Texture C_T_ID08;
sf::Texture C_T_ID09;
sf::Texture C_T_ID10;
sf::Texture C_T_ID11;
sf::Texture C_T_ID12;
sf::Sprite Character1_Sprite;
sf::Sprite Character2_Sprite;
C_T_ID00.loadFromFile("CharacterTextures/Luigi.png");
C_T_ID01.loadFromFile("CharacterTextures/Blank.png");
C_T_ID02.loadFromFile("CharacterTextures/Aizen.png");
C_T_ID03.loadFromFile("CharacterTextures/Blank.png");
C_T_ID04.loadFromFile("CharacterTextures/Blank.png");
C_T_ID05.loadFromFile("CharacterTextures/Shadow.png");
C_T_ID06.loadFromFile("CharacterTextures/Blank.png");
C_T_ID07.loadFromFile("CharacterTextures/Blank.png");
C_T_ID08.loadFromFile("CharacterTextures/Roxas.png");
C_T_ID09.loadFromFile("CharacterTextures/Blank.png");
C_T_ID10.loadFromFile("CharacterTextures/Blank.png");
C_T_ID11.loadFromFile("CharacterTextures/Blank.png");
C_T_ID12.loadFromFile("CharacterTextures/Blank.png");
