#pragma once

const std::string L_ID00 = "level 1";
const std::string L_ID01 = "level 2";
const std::string L_ID02 = "level 3";
const std::string L_ID03 = "level 4";
const std::string L_ID04 = "level 5";
const std::string L_ID05 = "level 6";
const std::string L_ID06 = "level 7";
const std::string L_ID07 = "level 8";
bool LevelUnlock_ID00;
bool LevelUnlock_ID01;
bool LevelUnlock_ID02;
bool LevelUnlock_ID03;
bool LevelUnlock_ID04;
bool LevelUnlock_ID05;
bool LevelUnlock_ID06;
bool LevelUnlock_ID07;
sf::Texture L_T_ID00;
sf::Texture L_T_ID01;
sf::Texture L_T_ID02;
sf::Texture L_T_ID03;
sf::Texture L_T_ID04;
sf::Texture L_T_ID05;
sf::Texture L_T_ID06;
sf::Texture L_T_ID07;
sf::Texture LB_T_ID00;
sf::Texture LB_T_ID01;
sf::Texture LB_T_ID02;
sf::Texture LB_T_ID03;
sf::Texture LB_T_ID04;
sf::Texture LB_T_ID05;
sf::Texture LB_T_ID06;
sf::Texture LB_T_ID07;
sf::Sprite LevelBackground_Sprite;
sf::Sprite Level_Sprite;
L_T_ID00.loadFromFile("LevelTextures/L_ID00.png");
L_T_ID01.loadFromFile("LevelTextures/Blank.png");
L_T_ID02.loadFromFile("LevelTextures/Blank.png");
L_T_ID03.loadFromFile("LevelTextures/Blank.png");
L_T_ID04.loadFromFile("LevelTextures/Blank.png");
L_T_ID05.loadFromFile("LevelTextures/Blank.png");
L_T_ID06.loadFromFile("LevelTextures/Blank.png");
L_T_ID07.loadFromFile("LevelTextures/Blank.png");
LB_T_ID00.loadFromFile("LevelTextures/Blank.png");
LB_T_ID01.loadFromFile("LevelTextures/Blank.png");
LB_T_ID02.loadFromFile("LevelTextures/Blank.png");
LB_T_ID03.loadFromFile("LevelTextures/Blank.png");
LB_T_ID04.loadFromFile("LevelTextures/Blank.png");
LB_T_ID05.loadFromFile("LevelTextures/Blank.png");
LB_T_ID06.loadFromFile("LevelTextures/Blank.png");
LB_T_ID07.loadFromFile("LevelTextures/Blank.png");